### ISSUE TITLE
Background change

### ISSUE THREAD

**Issue by MrWhiteFlamesYT-dev** [PadowYT2/Nameless-Argon#11]
Hey PaddowYT2

Allow use to change the Blue background at the top to custom image/color.
as when dark mode comes to mke it so that you can choose custom background to ease the eyes as that will be brighter thatn the theme itself.

Kind Regards
MrWhiteFlamesYT.

**Comment by PadowYT2** [comment]
1. Not sure how will I'm going to make a custom image, because it is not possible. Why? There are no `Settings` for panel templates
2. When dark mode will be switched the color of the background and button will switch to primary

**Comment by MrWhiteFlamesYT-dev** [comment]
dang, ok i thought it might have been able to be done.
and cool i thought some colors might have stayd the same for dark mode.
