### ISSUE TITLE
Add Modules - Store, Tickets, Donate, Tebex, DiscordBotWidget

### ISSUE THREAD

**Issue by IkiaeM** [PadowYT2/Nameless-Argon#2]
It would be really cool if you added these modules in a future update.

- [x] Store
- [x] Donate
- Tickets
- [ ] Tebex
- [x] DiscordBotWidget

Otherwise the theme is beautiful. I've never seen it before and I really like it. If you can add the modules I put in it would be great my use 😊

Thanks for this work

**Comment by PadowYT2** [comment]
Tickets won't be a thing
1) It is legacy
2) The owner of it is inactive

**Comment by IkiaeM** [comment]
This is a new addon to PartyDragon.
There is another one called "donation" this one is called "Donate" here: https://namelessmc.com/resources/resource/177-donate-module/
The module you currently support is "donation", it would be really cool if you added "Donate" 😊

It's a shame about Tickets.

**Comment by PadowYT2** [comment]
> This is a new addon to PartyDragon. There is another one called "donation" this one is called "Donate" here: https://namelessmc.com/resources/resource/177-donate-module/ The module you currently support is "donation", it would be really cool if you added "Donate" blush
> 
> It's a shame about Tickets. Did you contact the Dev via his discord server for the Tickets module? Here is his discord : https://discord.gg/5CCku34

That's coldfire's dev server, someone else made the resource
