### ISSUE TITLE
Problem with modules - Staff, Chatbox, 

### ISSUE THREAD

**Issue by IkiaeM** [PadowYT2/Nameless-Argon#3]
There is a visual problem on these 2 modules, the page of the module comes on top of the mune and everything else.

- Staff
- Chatbox

Thanks for this work

<img width="1920" alt="Capture d’écran 2021-12-12 à 18 12 29" src="https://user-images.githubusercontent.com/64362443/145722273-4ce2a14d-4bf5-4bff-8011-44bf5d657556.png">
<img width="1920" alt="Capture d’écran 2021-12-12 à 18 12 44" src="https://user-images.githubusercontent.com/64362443/145722281-179b3da5-ae12-43fd-b175-8fba83d451ec.png">

**Comment by PadowYT2** [comment]
Staff and chatbox cannot be done, because the .tpl file is built into the module and not in the panel template

**Comment by IkiaeM** [comment]
Another StaffCP template supports its 2 pages by creating .tpl files

Here they are: https://jmp.sh/6RZwxkH

**Comment by PadowYT2** [comment]
Hm, I'll try then

**Comment by PadowYT2** [comment]
Nope, tried doing, nothing worked
